const pages=[...document.querySelectorAll('.page')];const navItems=[...document.querySelectorAll('.nav-item')];const pageTitle=document.getElementById('pageTitle');const sidebar=document.getElementById('sidebar');
const titles={overview:'Overview',map:'Live Risk Map',assistant:'AI Assistant',evacuation:'Evacuation',shelters:'Shelters & Services',reports:'Citizen Reports',command:'Command Center',analytics:'Analytics'};
function go(page){pages.forEach(p=>p.classList.toggle('active',p.id===page));navItems.forEach(n=>n.classList.toggle('active',n.dataset.page===page));pageTitle.textContent=titles[page]||'Overview';window.scrollTo({top:0,behavior:'smooth'});sidebar.classList.remove('open')}
navItems.forEach(n=>n.addEventListener('click',()=>go(n.dataset.page)));document.querySelectorAll('[data-go]').forEach(el=>el.addEventListener('click',()=>go(el.dataset.go)));document.getElementById('mobileMenu').addEventListener('click',()=>sidebar.classList.toggle('open'));
const drawer=document.getElementById('alertDrawer');document.getElementById('alertBtn').addEventListener('click',()=>drawer.classList.add('open'));document.getElementById('closeDrawer').addEventListener('click',()=>drawer.classList.remove('open'));
function toast(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
document.getElementById('simulateAlert').addEventListener('click',()=>{const list=document.getElementById('overviewAlerts');const row=document.createElement('div');row.className='alert-row critical';row.innerHTML='<span class="alert-level">CRITICAL</span><div><b>New road blockage detected near Zone C</b><p>AI verified 2 reports with 91% confidence.</p></div><time>now</time>';list.prepend(row);toast('Live situation update added')});
const chat=document.getElementById('chat'),chatInput=document.getElementById('chatInput'),chatForm=document.getElementById('chatForm');
const replies=[['is my area safe','Your selected area is currently <b>CRITICAL</b> (87/100). Heavy rainfall, low elevation, rising water and road-access issues are the biggest contributors. Avoid low-lying roads and prepare to move toward the nearest verified shelter.'],['find the nearest shelter','The nearest recommended shelter is <b>Central Community Shelter</b>, approximately 1.8 km away. Current occupancy is 320 / 500 (64%). It has a medical desk, drinking water and charging facilities.'],['explain my risk','Your risk score is <b>87/100</b> because several signals agree: rainfall is high, the water level is rising, the area is low-lying, population exposure is elevated and road accessibility is deteriorating.'],['safest evacuation route','RAKSHA recommends <b>Route B</b>. It is 2.4 km and about 8 minutes. Route A is shorter but crosses a high-risk flood segment, so it is not recommended.']];
const normalize=s=>s.toLowerCase().replace(/[?!.,]/g,'').trim();function addMessage(text,kind='ai'){const el=document.createElement('div');el.className=`msg ${kind}`;if(kind==='ai')el.innerHTML=`<div class="msg-avatar">R</div><div><span class="msg-label">RAKSHA</span><p>${text}</p></div>`;else el.innerHTML=`<div style="margin-left:auto"><span class="msg-label">YOU</span><p style="background:#171b22;border-radius:12px 5px 12px 12px">${text}</p></div>`;chat.appendChild(el);chat.scrollTop=chat.scrollHeight}
function answerFor(q){const n=normalize(q);const m=replies.find(([k])=>n.includes(k));if(m)return m[1];if(n.includes('route')||n.includes('road'))return replies[3][1];if(n.includes('shelter'))return replies[1][1];if(n.includes('risk')||n.includes('safe'))return replies[0][1];return 'Based on the current RAKSHA data, your area is under <b>CRITICAL</b> risk. I can help with the safest route, nearest shelter, risk explanation or emergency actions.'}
chatForm.addEventListener('submit',e=>{e.preventDefault();const q=chatInput.value.trim();if(!q)return;addMessage(q,'user');chatInput.value='';setTimeout(()=>addMessage(answerFor(q)),450)});document.querySelectorAll('.quick-prompts button').forEach(b=>b.addEventListener('click',()=>{chatInput.value=b.dataset.prompt;chatForm.dispatchEvent(new Event('submit'))}));
document.getElementById('startRoute').addEventListener('click',()=>toast('Navigation started — following safest route B'));document.getElementById('applyRec').addEventListener('click',()=>toast('AI recommendation applied to response plan'));
const browseBtn=document.getElementById('browseBtn'),fileInput=document.getElementById('fileInput'),fileName=document.getElementById('fileName'),uploadBox=document.getElementById('uploadBox');browseBtn.addEventListener('click',()=>fileInput.click());fileInput.addEventListener('change',()=>{fileName.textContent=fileInput.files.length?`Selected: ${fileInput.files[0].name}`:''});['dragenter','dragover'].forEach(evt=>uploadBox.addEventListener(evt,e=>{e.preventDefault();uploadBox.style.borderColor='rgba(255,106,61,.55)'}));['dragleave','drop'].forEach(evt=>uploadBox.addEventListener(evt,e=>{e.preventDefault();uploadBox.style.borderColor='#3a4755'}));uploadBox.addEventListener('drop',e=>{const f=e.dataTransfer.files?.[0];if(f&&f.type.startsWith('image/')){fileName.textContent=`Selected: ${f.name}`}});
document.getElementById('submitReport').addEventListener('click',()=>{const result=document.getElementById('submitResult');result.textContent='✓ Report received. Demo AI verification: Flooded road detected · Confidence 91% · Risk engine queued an update.';result.classList.add('show');toast('Incident submitted for AI verification')});
setTimeout(()=>{const live=document.querySelector('.mode-pill .status-dot');if(live)live.style.boxShadow='0 0 0 5px rgba(71,212,155,.12), 0 0 12px rgba(71,212,155,.4)'},900);
